In [18]:
import numpy as np
import os
import tifffile
import matplotlib.path

In [2]:
pwd

'D:\\BIO\\4th year masters\\Project 3\\Github\\PombeTrack\\library'

In [3]:
pathh="../../movie_4_MMStack_Pos55.ome.tif"

In [4]:
with tifffile.TiffFile(pathh) as im_frames:
    im_metadata = im_frames.imagej_metadata

In [6]:
im_metadata["slices"]

3

In [ ]:
coords = np.array([(n.x, n.y) for n in self.balloon_obj.nodes])
np.save(coords_path, coords)

In [54]:
a=np.array([[1.,1.],[1.,3.],[3.,3.],[3.,1.]])#[::2]

In [62]:
a[1,:].reshape(1,2)

array([[1., 3.]])

In [63]:
np.append(a,a[1,:].reshape(1,2),axis=0)

array([[1., 1.],
       [1., 3.],
       [3., 3.],
       [3., 1.],
       [1., 3.]])

In [17]:
4 not in range(5,9) or 5 not in range(5,9)

True

In [48]:
pp=matplotlib.path.Path(a,closed=True)
pp

Path(array([[1., 1.],
       [1., 3.],
       [3., 3.],
       [3., 1.],
       [1., 1.]]), array([ 1,  2,  2,  2, 79], dtype=uint8))

In [65]:
pp.contains_point([1.05,2])

True

In [69]:
np.array([2.3,532.2]).astype(int)

array([  2, 532])